### ISSUE TITLE
Update for 1.0.1734.0?

### ISSUE THREAD

**Issue by Hazmi35** [E66666666/GTAVVehicleControl#1]
The title says it all
some remote functions will make the mod crashes.

**Comment by Hazmi35** [comment]
Umm, hello? @E66666666

**Comment by ikt32** [comment]
You can use the automatic build. Not sure if it works though.

There are a bunch of other issues, but there are also other projects and things in life that take priority, so I can't give this a proper update for the while.

**Comment by Hazmi35** [comment]
Closing, because remote functions that make the mod crashes works as intended again
