### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by Michael21107** [E66666666/GTAVVehicleControl#4]
rename the repo's name to `GTAVRemoteVehicleControl` to avoid possible confusion with [Toxic Scams' Vehicle Control](https://www.gta5-mods.com/scripts/vehicle-control) and better describe its function

**Comment by ikt32** [comment]
This repository was created in April 2018, predating that mod. Not going to consider the idea.

**Comment by Michael21107** [comment]
copy that 👍
